# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datree < Formula
  desc ""
  homepage "https://datree.io/"
  version "0.10.0-staging"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/datreeio/datree/releases/download/0.10.0-staging/datree-cli_0.10.0-staging_Darwin_x86_64.zip"
    sha256 "7262d349902bb60551838c5c1cdab36bf452eaac5f1abb8e6831d2a52478a708"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/datreeio/datree/releases/download/0.10.0-staging/datree-cli_0.10.0-staging_Linux_x86_64.zip"
    sha256 "50b4931543e8477fe47ccea5cf9e1d29ec5458ccf1aef6691b11391b34969969"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/datreeio/datree/releases/download/0.10.0-staging/datree-cli_0.10.0-staging_Linux_arm64.zip"
    sha256 "8478445c6f71fb57b3cfa6291158391cfe889440e8adea9f4fa60db4b8e3cc75"
  end

  def install
    bin.install "datree"
  end
end
