# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datree < Formula
  desc ""
  homepage "https://datree.io/"
  version "0.8.0-staging"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/datreeio/datree/releases/download/0.8.0-staging/datree-cli_0.8.0-staging_Darwin_x86_64.zip"
    sha256 "1898d09a50b2f06a5276091e8a7fa72357896769eb5ef0743cbc0566455c85af"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/datreeio/datree/releases/download/0.8.0-staging/datree-cli_0.8.0-staging_Linux_x86_64.zip"
    sha256 "c3dc3eb79ecf341da6bcdf592941614f3cb45e927d5ab1ba43f96318fbcc2ba2"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/datreeio/datree/releases/download/0.8.0-staging/datree-cli_0.8.0-staging_Linux_arm64.zip"
    sha256 "770c1e6228af4f0cf92c36b99b2f20b06f2ce7907aa799bc8a7f703bf30744da"
  end

  def install
    bin.install "datree"
  end
end
